services:
  db:
    image: docker.io/postgres:16.3-alpine3.20
    shm_size: 128mb
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev